### ISSUE TITLE
Setup limit switches

### ISSUE THREAD

**Issue by xinkecf35** [Pitt-RAS/erasinator-2018#3]
Since we are using limit switches to detect the edge of the board, we must have switches set up in the code to respond to when the limit switches are hit. The core behavior that must be implemented for now is that it stops the robot. This behavior must also be implemented using interrupt handlers as to not halt program execution of time-critical processes, namely odometry.

This must code must be in its own header and implementation file, as to ease integration later.

**Comment by BenRushin** [comment]
Solved
